### ISSUE TITLE
Updating the Platform infrastructure to handle the new evidence data model

### ISSUE THREAD

**Issue by DSuveges** [opentargets/platform#1275]
In an effort to streamline the evidence data model, we have to develop a new JSON schema that all evidence sources will have to adapt. So this epic captures all the efforts needed to be done in this space:

* Developing a new schema that represents the new data model
   - [x] Update [JSON schema](https://github.com/opentargets/json_schema)
   - [x] Update [JSON schema validator](https://github.com/opentargets/validator/)
* Updating all [datasource parsers](https://github.com/opentargets/evidence_datasource_parsers) we are maintaining:
    - [x] OT Genetics Portal
    - [x] CRISPR
    - [x] ClinGen
    - [x] Gene2Phenotype
    - [x] GenomicsEngland
    - [x] IntOGen
    - [x] PhenoDigm
    - [x] PROGENY
    - [x] PheWAS
    - [x] SLPEnrich
    - [x] SystemsBiology
* Streamline process of running all parsers (e.g. snakemake file)
* Updating platform input support.
