### ISSUE TITLE
Migrate graphQL queries in platform-app to GQL files

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1420]
After discussion derived from #1418, it was concluded that we should migrate as many queries as possible to .gql files.   

It was discussed that some queries were so concise that they were not moved to an outside file. We see a point now to separate them from the rest of the code. Also, some of the queries are dynamically changed, so we will need to consider the dynamic parameters for future applications (e.g. testing).

A list of the currently implemented GQL files:

```
❯ find platform-app -type f -name "*.gql"
platform-app/src/sections/evidence/CancerGeneCensus/sectionQuery.gql
platform-app/src/sections/evidence/OTGenetics/sectionQuery.gql
platform-app/src/sections/evidence/GenomicsEngland/sectionQuery.gql
platform-app/src/sections/evidence/EuropePmc/sectionQuery.gql
platform-app/src/sections/evidence/Phenodigm/sectionQuery.gql
platform-app/src/sections/evidence/Gene2Phenotype/sectionQuery.gql
platform-app/src/sections/evidence/IntOgen/sectionQuery.gql
platform-app/src/sections/target/ProteinInformation/sectionQuery.gql
platform-app/src/sections/target/ProteinInformation/summaryQuery.gql
platform-app/src/sections/target/Safety/summaryQuery.gql
platform-app/src/sections/target/ProteinInteractions/sectionQuery.gql
platform-app/src/sections/target/ProteinInteractions/summaryQuery.gql
platform-app/src/components/Search/SearchQuery.gql
platform-app/src/pages/SearchPage/SearchPageQuery.gql
```

Next, the queries that need to be migrated, resulting from the next query:

```
❯ find platform-app -type f -name '*.js' -exec grep -H "= gql\`" {} \;
```

- [ ] platform-app/src/sections/disease/RelatedDiseases/Body.js:const RELATED_DISEASES_QUERY = gql`
- [ ] platform-app/src/sections/disease/RelatedDiseases/Summary.js:const RELATED_DISEASES_SUMMARY_FRAGMENT = gql`
- [ ] platform-app/src/sections/disease/Phenotypes/Body.js:const PHENOTYPES_BODY_QUERY = gql`
- [ ] platform-app/src/sections/disease/Phenotypes/Summary.js:const PHENOTYPES_SUMMARY_FRAGMENT = gql`
- [ ] platform-app/src/sections/disease/KnownDrugs/Body.js:const KNOWN_DRUGS_BODY_QUERY = gql`
- [ ] platform-app/src/sections/disease/KnownDrugs/Summary.js:const KNOWN_DRUGS_SUMMARY_FRAGMENT = gql`
- [ ] platform-app/src/sections/disease/Ontology/Summary.js:const ONTOLOGY_SUMMARY_FRAGMENT = gql`
- [ ] platform-app/src/sections/evidence/ClinGen/Body.js:const CLINGEN_QUERY = gql`
- [ ] platform-app/src/sections/evidence/ClinGen/Summary.js:const CLINGEN_SUMMARY_FRAGMENT = gql`
- [ ] platform-app/src/sections/evidence/EVA/Body.js:const EVA_QUERY = gql`
- [ ] platform-app/src/sections/evidence/EVA/Summary.js:const EVA_SUMMARY = gql`
- [ ] platform-app/src/sections/evidence/PheWASCatalog/Body.js:const PHEWAS_CATALOG_QUERY = gql`
- [ ] platform-app/src/sections/evidence/PheWASCatalog/Summary.js:const PHEWAS_CATALOG_SUMMARY = gql`
- [ ] platform-app/src/sections/evidence/CancerGeneCensus/Summary.js:const CANCER_GENE_CENSUS_SUMMARY = gql`
- [ ] platform-app/src/sections/evidence/OTGenetics/Summary.js:const OPEN_TARGETS_GENETICS_SUMMARY_FRAGMENT = gql`
- [ ] platform-app/src/sections/evidence/GenomicsEngland/Summary.js:const GENOMICS_ENGLAND_SUMMARY_FRAGMENT = gql`
- [ ] platform-app/src/sections/evidence/CRISPR/Body.js:const CRISPR_QUERY = gql`
- [ ] platform-app/src/sections/evidence/CRISPR/Summary.js:const CRISPR_SUMMARY = gql`
- [ ] platform-app/src/sections/evidence/UniProtLiterature/Body.js:const UNIPROT_LITERATURE_QUERY = gql`
- [ ] platform-app/src/sections/evidence/UniProtLiterature/Summary.js:const UNIPROT_LITERATURE_SUMMARY = gql`
- [ ] platform-app/src/sections/evidence/ExpressionAtlas/Body.js:const EXPRESSION_ATLAS_QUERY = gql`
- [ ] platform-app/src/sections/evidence/ExpressionAtlas/Summary.js:const EXPRESSION_ATLAS_SUMMARY = gql`
- [ ] platform-app/src/sections/evidence/SysBio/Body.js:const INTOGEN_QUERY = gql`
- [ ] platform-app/src/sections/evidence/SysBio/Summary.js:const SYSBIO_SUMMARY_FRAGMENT = gql`
- [ ] platform-app/src/sections/evidence/Chembl/Body.js:const CHEMBL_QUERY = gql`
- [ ] platform-app/src/sections/evidence/Chembl/Summary.js:const CHEMBL_SUMMARY_FRAGMENT = gql`
- [ ] platform-app/src/sections/evidence/EVASomatic/Body.js:const EVA_SOMATIC_QUERY = gql`
- [ ] platform-app/src/sections/evidence/EVASomatic/Summary.js:const EVA_SOMATIC_SUMMARY = gql`
- [ ] platform-app/src/sections/evidence/EuropePmc/Summary.js:const EUROPE_PMC_SUMMARY_FRAGMENT = gql`
- [ ] platform-app/src/sections/evidence/Progeny/Body.js:const PROGENY_QUERY = gql`
- [ ] platform-app/src/sections/evidence/Progeny/Summary.js:const PROGENY_SUMMARY_FRAGMENT = gql`
- [ ] platform-app/src/sections/evidence/SlapEnrich/Body.js:const SLAPENRICH_QUERY = gql`
- [ ] platform-app/src/sections/evidence/SlapEnrich/Summary.js:const SLAPENRICH_SUMMARY_FRAGMENT = gql`
- [ ] platform-app/src/sections/evidence/Phenodigm/Summary.js:const PHENODIGM_SUMMARY_FRAGMENT = gql`
- [ ] platform-app/src/sections/evidence/Gene2Phenotype/Summary.js:const GENE_2_PHENOTYPE_SUMMARY_FRAGMENT = gql`
- [ ] platform-app/src/sections/evidence/IntOgen/Summary.js:const INTOGEN_SUMMARY_FRAGMENT = gql`
- [ ] platform-app/src/sections/evidence/Reactome/Body.js:const REACTOME_QUERY = gql`
- [ ] platform-app/src/sections/evidence/Reactome/Summary.js:const REACTOME_SUMMARY = gql`
- [ ] platform-app/src/sections/target/Tep/Summary.js:const TEP_SUMMARY_FRAGMENT = gql`
- [ ] platform-app/src/sections/target/CancerHallmarks/Summary.js:const CANCER_HALLMARKS_SUMMARY_FRAGMENT = gql`
- [ ] platform-app/src/sections/target/ProteinInformation/Summary.js:const PROTEIN_INFORMATION_SUMMARY_FRAGMENT = gql`
- [ ] platform-app/src/sections/target/ChemicalProbes/Summary.js:const CHEMICAL_PROBES_SUMMARY_FRAGMENT = gql`
- [ ] platform-app/src/sections/target/KnownDrugs/Body.js:const KNOWN_DRUGS_BODY_QUERY = gql`
- [ ] platform-app/src/sections/target/KnownDrugs/Summary.js:const KNOWN_DRUGS_SUMMARY_FRAGMENT = gql`
- [ ] platform-app/src/sections/target/RelatedTargets/Body.js:const RELATED_TARGETS_QUERY = gql`
- [ ] platform-app/src/sections/target/RelatedTargets/Summary.js:const RELATED_TARGETS_SUMMARY_FRAGMENT = gql`
- [ ] platform-app/src/sections/target/CancerBiomarkers/Body.js:const BIOMARKERS_QUERY = gql`
- [ ] platform-app/src/sections/target/CancerBiomarkers/Summary.js:const CANCER_BIOMARKERS_SUMMARY_FRAGMENT = gql`
- [ ] platform-app/src/sections/target/Tractability/Summary.js:const TRACTABILITY_SUMMARY_FRAGMENT = gql`
- [ ] platform-app/src/sections/target/MousePhenotypes/Summary.js:const MOUSE_PHENOTYPES_SUMMARY_FRAGMENT = gql`
- [ ] platform-app/src/sections/target/Expression/SummaryTab.js:const EXPRESSION_QUERY = gql`
- [ ] platform-app/src/sections/target/Expression/Summary.js:const EXPRESSION_SUMMARY_FRAGMENT = gql`
- [ ] platform-app/src/sections/target/Pathways/Summary.js:const PATHWAYS_SUMMARY_FRAGMENT = gql`
- [ ] platform-app/src/sections/target/GeneOntology/Summary.js:const GENE_ONTOLOGY_SUMMARY_FRAGMENT = gql`
- [ ] platform-app/src/sections/drug/KnownDrugs/Body.js:const KNOWN_DRUGS_BODY_QUERY = gql`
- [ ] platform-app/src/sections/drug/KnownDrugs/Summary.js:const KNOWN_DRUGS_SUMMARY_FRAGMENT = gql`
- [ ] platform-app/src/sections/drug/Indications/Body.js:const INDICATIONS_QUERY = gql`
- [ ] platform-app/src/sections/drug/Indications/Summary.js:const INDICATIONS_SUMMARY_FRAGMENT = gql`
- [ ] platform-app/src/sections/drug/AdverseEvents/Body.js:const ADVERSE_EVENTS_QUERY = gql`
- [ ] platform-app/src/sections/drug/AdverseEvents/Summary.js:const ADVERSE_EVENTS_SUMMARY_FRAGMENT = gql`
- [ ] platform-app/src/sections/drug/MechanismsOfAction/Body.js:const MECHANISMS_OF_ACTION_QUERY = gql`
- [ ] platform-app/src/sections/drug/MechanismsOfAction/Summary.js:const MECHANISM_OF_ACTION_SUMMARY_FRAGMENT = gql`
- [ ] platform-app/src/pages/DrugPage/Profile.js:const DRUG_PROFILE_QUERY = gql`
- [ ] platform-app/src/pages/DrugPage/ProfileHeader.js:const DRUG_PROFILE_HEADER_FRAGMENT = gql`
- [ ] platform-app/src/pages/DrugPage/DrugPage.js:const DRUG_PAGE_QUERY = gql`
- [ ] platform-app/src/pages/TargetPage/ClassicAssociationsTable.js:const TARGET_ASSOCIATIONS_QUERY = gql`
- [ ] platform-app/src/pages/TargetPage/Profile.js:const TARGET_PROFILE_QUERY = gql`
- [ ] platform-app/src/pages/TargetPage/ProfileHeader.js:const TARGET_PROFILE_HEADER_FRAGMENT = gql`
- [ ] platform-app/src/pages/TargetPage/TargetPage.js:const TARGET_PAGE_QUERY = gql`
- [ ] platform-app/src/pages/TargetPage/Wrapper.js:const ASSOCIATIONS_VIZ_QUERY = gql`
- [ ] platform-app/src/pages/TargetPage/ClassicAssociations.js:const TARGET_FACETS_QUERY = gql`
- [ ] platform-app/src/pages/DiseasePage/ClassicAssociationsTable.js:const DISEASE_ASSOCIATIONS_QUERY = gql`
- [ ] platform-app/src/pages/DiseasePage/Profile.js:const DISEASE_PROFILE_QUERY = gql`
- [ ] platform-app/src/pages/DiseasePage/DiseasePage.js:const DISEASE_PAGE_QUERY = gql`
- [ ] platform-app/src/pages/DiseasePage/ProfileHeader.js:const DISEASE_PROFILE_HEADER_FRAGMENT = gql`
- [ ] platform-app/src/pages/DiseasePage/ClassicAssociations.js:const DISEASE_FACETS_QUERY = gql`
- [ ] platform-app/src/pages/EvidencePage/Profile.js:const EVIDENCE_PROFILE_QUERY = gql`
- [ ] platform-app/src/pages/EvidencePage/EvidencePage.js:const EVIDENCE_PAGE_QUERY = gql`

**Comment by mkarmona** [comment]
@d0choa thanks! this will be really convenient to help with systematic API testing.

**Comment by andrewhercules** [comment]
Epic ticket closed as the work noted in tickets #1526, #1527, #1528, and #1529 has been completed and merged into `main`
