### ISSUE TITLE
Update Platform issue tracker

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1592]
With the recent launch of the next-gen Platform, we should update the content of Platform issue tracker to encourage more contributions and collaboration. 

This update will require:

- New content for the README.md file
- A new Code of Conduct
- A new Contribution Guidelines  

The Code of Conduct and Contribution Guidelines can be similar to what is available in the [platform-app](https://github.com/opentargets/platform-app/tree/main/docs).

**Comment by ktsirigos** [comment]
- [ ] New content for the README.md file
- [ ] A new Code of Conduct
- [ ] A new Contribution Guidelines

**Comment by ktsirigos** [comment]
work done and merged
