### ISSUE TITLE
Create a reproducible Conda environment for evidence_datasource_parsers

### ISSUE THREAD

**Issue by tskir** [opentargets/platform#1628]
There are currently two issues with [`conda-env.yml`](https://github.com/opentargets/evidence_datasource_parsers/blob/master/envs/conda-env.yml):

### Cross-platform reproducibility
First, I cannot reproduce the environment on my machine with `conda env create -f envs/conda-env.yml`:
```
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - numpy-base==1.19.2=py37hcfb5961_0
  - mkl-service==2.3.0=py37h9ed2024_0
  - kubernetes-node==1.18.8=h321dcc0_0
[...]
```

The reason is that the environment was frozen on OSX, but I'm trying to build it in Linux, and by default the environment files created by `conda lock` are not cross-platform reproducible: https://github.com/conda/conda/issues/7311#issuecomment-442320274.

I tried simply removing the build prefixes, but this native solution does not resolve the problem as well, so the environment will have to be rebuilt from scratch with different parameters.

### Upgradeability
The environment is currently fully transitively pinned, with about 125 packages with their exact versions specified. This is in theory reproducible (barring the issue above), but has two issues:
1. Hard to upgrade the packages, because it causes complete chaos in the dependency versions;
2. Hard to tell apart direct and transitive dependencies, which over time will lead to accumulation of transitive dependencies which are no longer needed.

I'm planning to address this problem by having two files, as suggested in this [blog post.](https://pythonspeed.com/articles/conda-dependency-management/)
* The first one contains only direct dependencies with the exact versions pinned.
* The second file contains all dependencies, including transitive, again with the exact versions pinned.
* Each time the first file is changed, the second is re-generated using `conda lock` with the appropriate parameters.

**Comment by tskir** [comment]
### Task checklist
- [x] Investigate ways to handle reproducible Conda environments
- [x] Remove obsolete environment files
- [ ] Rebuild the environment
- [ ] Add instructions on maintaining the environment
- [ ] Submit the PR

**Comment by tskir** [comment]
### Summary of possible approaches

For discussion with @ireneisdoomed and @DSuveges.

It turns out that the tools for managing Conda/Python package environments have certain limitations:
* `conda env export` fundamentally cannot support cross-platform environments, even with the `--no-builds` flag suggested in the issue which I linked in the description. For example, when exporting on Linux with this flag, one of the transitive dependencies is `ld_impl_linux-64` which clearly will not work on OSX.
* `conda-lock` cannot manage PIP packages at all. At the same time, it is incompatible with `pip freeze` because Conda uses a different algorithm for version conflict resolution. For example, when installing `pyspark=2.4.0` with Conda, it also installs `py4j=0.10.8.1`, but for PIP these two versions are incompatible with each other.

Due to these limitations, it is not possible to create the environments which are, all at the same time:
* Cross-platform;
* Reproducible;
* Upgradeable;
* Support mixed Conda + PIP packages.

This means we have to drop at least one of these requirements. Some possible solutions are listed below.

#### 1. Drop cross-platform support
If we drop OSX support and only support Linux, standard `conda env export` approach can be used. However, this means that OSX users will not be able to reproduce the **locked** environment locally and will have to use e.g. Google Cloud.

#### 2. Drop reproducibility (version pinning)
Do not attempt to create a locked environment, simply re-create it as needed from the unversioned direct dependency file, and hope that things don't break too drastically, fixing the version conflicts as they appear.

#### 3. Drop Conda
Use PIP + `pip freeze`. If we ever need binaries (not currently needed by anything in the evidence_datasource_parsers repository), simply use Docker for that.

#### 4. Drop PIP
Always use Conda packages. This would allow us to use `conda-lock`. However, this means that we would have to package everything we need as a Conda package, including OnToma and any future dependencies.

**Comment by ireneisdoomed** [comment]
So the rationale of using conda environments in the first place has 2 origins:
- My first approach was to run the snakemake job in a dataproc cluster as a Pyspark job. Whenever you [create the cluster in dataproc](https://cloud.google.com/dataproc/docs/tutorials/python-configuration), you can specify the Python environment you want to set up via the `metadata` flag. For this you can either use pip or conda. After discussion with Miguel, he suggested to always use conda over pip given that the package management system is more complete.
- Snakemake has native support to deploy the pipeline with Conda. Reproducibility was one of the aims and the conda support seemed like the way to go. We might want to reconsider this approach and package the module in another way, or simply make it compatible for running it in the dataproc cluster like David showed us.

Back then I freezed the config yaml by calling `conda env export`. I’ve been reading about this other alternative to address the crossplatform issue which would be to simply generate a manual env.yaml (which is [the recommendation from conda-env](https://github.com/conda/conda/tree/master/conda_env)) or to generate the config only taking those modules that we have explicitly indicated with the `--from-history` flag (`conda env export --from-history` )

I’m not leaning towards one option or another, although I do find useful to make use the support for conda provided by snakemake. Happy to hear any of your inputs.

**Comment by tskir** [comment]
Taking into consideration comments from @ireneisdoomed and @DSuveges, decided to go with approach 1 and drop cross-platform support, as this is the least important feature compared to all others. Example PR is submitted to evidence_datasource_parsers and linked above.

**Comment by tskir** [comment]
### Remaining actions
- [ ] Update Travis configuration files to use the new Conda environment

**Comment by tskir** [comment]
Additional caveat to keep in mind: Conda environments cannot be cached by Travis, so the environment configuration step alone takes about 3 minutes. Otherwise, the approach does seem to work.
