### ISSUE TITLE
Roadmap: OTAR015 - Integrate Cancer Dependency Map as Evidence

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#163]
@MichaelaEBI commented on [Wed Jul 04 2018](https://github.com/opentargets/data_pipeline/issues/292)

The Cancer Dependency Project Paper has been submitted and after the meeting on June 22nd, 2018, Francesco made the manuscript and data available to us so that we can start defining how the data will fit into the Open Targets Platform.

- [x] Read Cancer DepMap paper & become familiar with the data (#78)
- [x] Define inclusion (#276)
- [x] Scoring of the data.
- [x] Specify backend and frontend implementation details.
- [x] Implement temporary solution to provide users with link to Project Score website (#464)
- [x] Implement in data_pipeline.
- [x] Implement data table on evidence page within the `Pathways and systems biology` tab (#466)

**Comment by ElaineMcA** [comment]
Closing epic as complete post 19.04 release.
