### ISSUE TITLE
Resolve ambiguous literature matches in post-processing step using manuscript context

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1659]
The current literature grounding uses all available synonyms for(T/D/Dr).

This can produce clashes when the same synonym or name is defined in more than one instance of the same entity type. While we have added some heuristics to for example prioritise gene symbols over other gene names, we still have a decent number of ambiguous results in all entities.

The next query in the `matches` dataset (21.06) illustrates the problem: 

```python
(
    matches
    .groupBy("label", "type")
    .agg(F.countDistinct(F.col("keywordId")).alias("distinctGroundedIdCount"),
         F.collect_set(F.col("keywordId")).alias("distinctGroundedIds"),
         F.countDistinct(F.col("pmid")).alias("distinctPMIDs"))
    .sort(F.col("distinctGroundedIdCount").desc())
    .persist()
    .filter(F.col("distinctPMIDs") > 50)
    .show(20)
)

```

```
+--------+----+-----------------------+--------------------+-------------+
|   label|type|distinctGroundedIdCount| distinctGroundedIds|distinctPMIDs|
+--------+----+-----------------------+--------------------+-------------+
|     TEC|  GP|                    745|[ENSG00000280665,...|          221|
|     Tec|  GP|                    745|[ENSG00000280665,...|          711|
|      31|  GP|                     65|[ENSG00000005189,...|           61|
|      U3|  GP|                     50|[ENSG00000212598,...|          177|
|      U6|  GP|                     33|[ENSG00000283564,...|         1243|
|   Nor-1|  GP|                     28|[ENSG00000119508,...|           90|
|   nor-1|  GP|                     28|[ENSG00000119508,...|           88|
|     S-1|  GP|                     27|[ENSG00000119943,...|          192|
|       1|  GP|                     26|[ENSG00000119943,...|         3878|
|      .1|  GP|                     26|[ENSG00000119943,...|          464|
|      -1|  GP|                     26|[ENSG00000119943,...|         5996|
|     ́-1|  GP|                     26|[ENSG00000119943,...|           76|
|      -3|  GP|                     22|[ENSG00000106484,...|          976|
|      .3|  GP|                     22|[ENSG00000106484,...|           84|
|       3|  GP|                     22|[ENSG00000106484,...|         3028|
|   his-3|  GP|                     22|[ENSG00000106484,...|          119|
|rotamase|  GP|                     14|[ENSG00000122642,...|          117|
|  PPiase|  GP|                     12|[ENSG00000137168,...|           51|
|  PPIase|  GP|                     12|[ENSG00000137168,...|         1208|
|     p55|  GP|                     10|[ENSG00000067182,...|         2916|
+--------+----+-----------------------+--------------------+-------------+
only showing top 20 rows
```

Note: Don't worry about the `TECs` they will be fixed once the new target object kicks in. Ensembl adds TEC as a placeholder synonym and causes issues on our side.  

`p55` is a good example on how, a label that was used to refer to proteins with a molecular weight of 55kDa is still been used in by 2916 publications to refer to multiple proteins. Hopefully, the same manuscripts will have grounded the right entity within the 10 possibilities. 

We want to design a prototype script (e.g. pyspark) that inputs the matches dataset and produces an output matches dataset in which incorrect ambiguous results have been excluded.

The idea to explore, is whether other matches in the same sentence, section or manuscript can disambiguate the correct match. For example, is expected that when a given acronym is used in the manuscript, the long name is also available somewhere in the text. By using the context we expect to resolve some ambiguous matches in a magnitude still to be determined.

We are aiming this prototype to eventually be integrated in the literature pipeline in Scala.

**Comment by DSuveges** [comment]
Some of the ambiguously grounded disease terms:

```
+------------------------+-----------------------------------------------------------+-----+------------------------------------------------------------------------------------------------------+
|label                   |keywords                                                   |count|labels                                                                                                |
+------------------------+-----------------------------------------------------------+-----+------------------------------------------------------------------------------------------------------+
|ACE                     |[Orphanet_946, Orphanet_36, EFO_0007129]                   |3    |[Acrocephalosyndactyly, Acrocallosal syndrome, acute chest syndrome]                                  |
|ACS                     |[Orphanet_946, Orphanet_36, EFO_0007129]                   |3    |[Acrocephalosyndactyly, Acrocallosal syndrome, acute chest syndrome]                                  |
|APE                     |[EFO_0004533, MONDO_0017278, Orphanet_320]                 |3    |[alkaline phosphatase measurement, autoimmune polyendocrinopathy, Apparent mineralocorticoid excess]  |
|CA                      |[Orphanet_209908, EFO_0009860, EFO_0000311]                |3    |[Childhood apraxia of speech, chromosomal aberration frequency, cancer]                               |
|CAS                     |[Orphanet_209908, EFO_0009860, EFO_0000311]                |3    |[Childhood apraxia of speech, chromosomal aberration frequency, cancer]                               |
|CHS                     |[Orphanet_2686, Orphanet_167, EFO_0009205]                 |3    |[Cyclic neutropenia, Chédiak-Higashi syndrome, Corpuscular Hemoglobin Content]                        |
|Colon cancer            |[EFO_0000365, MONDO_0021063, EFO_1001950, EFO_0004288]     |4    |[colorectal adenocarcinoma, malignant colon neoplasm, colon carcinoma, colonic neoplasm]              |
|DM                      |[EFO_0010133, EFO_0000398, EFO_0000400]                    |3    |[diabetic maculopathy, dermatomyositis, diabetes mellitus]                                            |
|ES                      |[EFO_0000174, MONDO_0017387, EFO_0009200]                  |3    |[Ewings sarcoma, epithelioid sarcoma, Eisenmenger syndrome]                                           |
|HP                      |[EFO_1000299, MONDO_0015540, Orphanet_79430, MONDO_0017853]|4    |[Hyperplastic Polyp, hemophagocytic syndrome, Hermansky-Pudlak syndrome, hypersensitivity pneumonitis]|
|Hp                      |[EFO_1000299, MONDO_0015540, Orphanet_79430, MONDO_0017853]|4    |[Hyperplastic Polyp, hemophagocytic syndrome, Hermansky-Pudlak syndrome, hypersensitivity pneumonitis]|
|MA                      |[Orphanet_562, EFO_1001806, EFO_1001037]                   |3    |[McCune-Albright syndrome, macrophage activation syndrome, meconium aspiration syndrome]              |
|MÃ                      |[Orphanet_562, EFO_1001806, EFO_1001037]                   |3    |[McCune-Albright syndrome, macrophage activation syndrome, meconium aspiration syndrome]              |
|MDS                     |[EFO_0000198, Orphanet_531, Orphanet_565]                  |3    |[myelodysplastic syndrome, Miller-Dieker syndrome, Menkes disease]                                    |
|Non-melanoma Skin Cancer|[EFO_0009260, MONDO_0002898, EFO_0009259]                  |3    |[non-melanoma skin carcinoma, skin cancer, skin carcinoma]                                            |
|Oral cancer             |[MONDO_0023644, EFO_0003868, EFO_0003871]                  |3    |[lip and oral cavity carcinoma, mouth neoplasm, tongue neoplasm]                                      |
|Pancreatic Cancer       |[EFO_0002618, EFO_1000359, EFO_0003860]                    |3    |[pancreatic carcinoma, Malignant Pancreatic Neoplasm, pancreatic neoplasm]                            |
|Pancreatic cancer       |[EFO_0002618, EFO_1000359, EFO_0003860]                    |3    |[pancreatic carcinoma, Malignant Pancreatic Neoplasm, pancreatic neoplasm]                            |
|Pinealomas              |[MONDO_0021232, MONDO_0003249, EFO_1000475]                |3    |[pineal body neoplasm, pineal gland cancer, Pineoblastoma]                                            |
|Testicular cancer       |[EFO_0005088, EFO_0004281, MONDO_0003510]                  |3    |[testicular carcinoma, testicular neoplasm, malignant testicular germ cell tumor]                     |
+------------------------+-----------------------------------------------------------+-----+------------------------------------------------------------------------------------------------------+
```

```python
(
    spark.read.parquet('gs://open-targets-pre-data-releases/21.06.5/output/literature/parquet/matches/')
    .limit(100_000)
    .filter(
        (col('type') == 'DS')
        & (col('ismapped') == True)
    )
    .select(col('label'), col('keywordId'))
    .distinct()
    .groupby(col('label'))
    .agg(
        collect_set(col('keywordId')).alias('keywords'),
        count(col('keywordId')).alias('count')
    )
    .filter(col('count') >= 3)
    .limit(20)
    .withColumn('labels', lool_up_ols(col('keywords')))
    .show(truncate=False)
)
```

**Comment by d0choa** [comment]
Comparison of the old vs new target synonyms can now be done in main vs production. This is just one example illustrating how many more synonyms we have and how necessary this work will be to prevent issues. 

<img width="1627" alt="Screenshot 2021-08-10 at 18 35 55" src="https://user-images.githubusercontent.com/5097586/128908056-581194e5-46a0-4800-80ec-b197aeab76a6.png">

**Comment by tskir** [comment]
### Tasks checklist
Initial iteration
- [ ] Investigate the dataset
- [ ] Implement the filtering approach
- [ ] Publish initial prototype
- [ ] Publish initial metrics on the number of records and mappings

Improvements
- [ ] Calculate mappings for known ambiguous terms such as p53
- [ ] Calculate mappings for an example gene above (APP)
- [ ] Publish the updated metrics

**Comment by tskir** [comment]
The repository is published here: **https://github.com/tskir/epmc-ambiguity.** It contains both the code and the initial results. It's a personal repository, because the approach is going to be reimplemented anyway.

**Comment by mkarmona** [comment]
It has been implemented.
