### ISSUE TITLE
Update Data Downloads page for 22.02 release

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1790]
As a **computational researcher** I want **an updated list of relevant datasets available for download** because **I will integrate these datasets into my own computational pipelines or analyses**

## Background

In previous releases, we have updated the Data Downloads page to list all relevant datasets. For example, see #1760. However, as noted in #1789, there are datasets that we do not include in the Data Downloads page (e.g. mouse phenotypes, safety, chemical probes, etc.)

## Tasks

- [x] Confirm with back-end team which datasets will be generated and made available by `platform-output-support` for 21.11
- [x] Update mouse phenotypes step to ETL  (opentargets/platform#1798)
- [x] Update [downloadData.json file](https://github.com/opentargets/platform-app/blob/main/src/pages/DownloadsPage/downloadData.json) file by running the following command (replacing `[xx.xx.x]` with the relevant ETL pipeline run version):
` gsutil cat 'gs://open-targets-pre-data-releases/[xx.xx.x]/output/etl/*/metadata/*/part-*.json' > downloadData.json`
- [x] Update the [dataset-mappings.json file](https://github.com/opentargets/platform-app/blob/main/src/pages/DownloadsPage/dataset-mappings.json) by changing the [dataset mapping file](https://docs.google.com/spreadsheets/d/1_266iRiVlCRii9cVLJ6__GCQVCw88QypEp6kXz8OcfQ), downloading as CSV, and [converting into JSON](https://www.convertcsv.com/csv-to-json.htm) 

## Acceptance tests

How do we know the task is complete? 

1. When I go to the Data Downloads page, I see a list of all relevant datasets available for download. The minimum required datasets include:
  - Target
  - Disease / Phenotype
  - Drug
  - Target - Disease evidence
  - Associations (x6 - direct/indirect, by score, source, type)
  - Target - molecular interactions
  - Target - evidence of molecular interactions
  - Target - baseline expression
  - Target - gene ontology
  - Target - mouse phenotypes
  - Disease/Phenotype - clinical signs and symptoms
  - Human Phenotype Ontology
  - Drug - mechanism of action
  - Drug - indications
  - Drug - pharmacovigiliance
  - Drug - withdrawn and black box warnings

**Comment by d0choa** [comment]
Correction. My mistake. Only the Mouse phenotypes dataset is missing

```
>>> target.select("chemicalProbes", "safetyLiabilities").printSchema()
root
 |-- chemicalProbes: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- control: string (nullable = true)
 |    |    |-- drugId: string (nullable = true)
 |    |    |-- id: string (nullable = true)
 |    |    |-- inchiKey: string (nullable = true)
 |    |    |-- isHighQuality: boolean (nullable = true)
 |    |    |-- mechanismOfAction: array (nullable = true)
 |    |    |    |-- element: string (containsNull = true)
 |    |    |-- origin: array (nullable = true)
 |    |    |    |-- element: string (containsNull = true)
 |    |    |-- probeMinerScore: string (nullable = true)
 |    |    |-- probesDrugsScore: string (nullable = true)
 |    |    |-- scoreInCells: string (nullable = true)
 |    |    |-- scoreInOrganisms: string (nullable = true)
 |    |    |-- targetFromSourceId: string (nullable = true)
 |    |    |-- urls: array (nullable = true)
 |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |-- niceName: string (nullable = true)
 |    |    |    |    |-- url: string (nullable = true)
 |-- safetyLiabilities: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- event: string (nullable = true)
 |    |    |-- eventId: string (nullable = true)
 |    |    |-- effects: array (nullable = true)
 |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |-- direction: string (nullable = true)
 |    |    |    |    |-- dosing: string (nullable = true)
 |    |    |-- biosample: array (nullable = true)
 |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |-- tissueLabel: string (nullable = true)
 |    |    |    |    |-- tissueId: string (nullable = true)
 |    |    |    |    |-- cellLabel: string (nullable = true)
 |    |    |    |    |-- cellFormat: string (nullable = true)
 |    |    |    |    |-- cellId: string (nullable = true)
 |    |    |-- datasource: string (nullable = true)
 |    |    |-- literature: string (nullable = true)
 |    |    |-- study: array (nullable = true)
 |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |-- name: string (nullable = true)
 |    |    |    |    |-- description: string (nullable = true)
 |    |    |    |    |-- type: string (nullable = true)
```

**Comment by andrewhercules** [comment]
@d0choa we currently do not list any literature data — should we also include it in the list on the Data Downloads page? If so, we will need to update `platform-output-support` to expose those datasets.

**Comment by cmalangone** [comment]
We generate and share the data for literature
Eg.
gs://open-targets-data-releases/21.09/output/literature/parquet

Currently just two of these directories are using to load data to CH (vectors and literatureIndex )
Due the size of the directory I just wondered 
*) Should we copy all these directories to the public bucket/ftp
*) should we add some of these directories to BQ?

**Comment by d0choa** [comment]
@andrewhercules at the moment the FE rely on the metadata produced to by the ETL to dynamically build the page. If #1793 is completed, it would be a lot easier to handle the literature outputs by POS and incorporate them in the downloads page.

We should monitor #1793 carefully to see how that work cascades into this.

We should as well flag all datasets that a) is of interest to the users b) has a manageable size for inclusion (in FTP, BQ, etc.)

**Comment by andrewhercules** [comment]
Rescoping for `22.02` release to ensure that the front-end is aware of all dataset files available for download

**Comment by andrewhercules** [comment]
Added to 22.02 release

**Comment by andrewhercules** [comment]
Ticket closed as changes for `22.02` have been merged into `main`
