### ISSUE TITLE
Review required evidence fields per data source

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/platform#1823]
As a **developer** I want **to reflect in the evidence JSON schema which fields are essential to every data source ** because **we want to catch unwanted data in an earlier stage.**

## Background
The schema for the `cancer_biomarkers` source has become more stringent after a reviewal of the required fields. We want to do the same thing for the rest of the evidence data sources.
As mentioned by @DSuveges:

> The original highly agnostic approach was based on the desire to be highly permissive on the data side. However this permissive behaviour likely cause issues downstream both BE and FE side.

## Tasks

- [x] Review if the fields in the ETL's config file are essential
- [x] Review other potential essential fields
- [x] Update the schema accordingly 

## Acceptance tests

1. Make sure all the latest evidence pass validation.
