### ISSUE TITLE
Add encore private data to the data release process

### ISSUE THREAD

**Issue by cmalangone** [opentargets/platform#1827]
As a developer I want to add encore private data to the data release process because encore data will be used by the partner platform instance.

## Background

Every time a new evidence resource is added to the data release, the BE team needs to verify PIS, ETL, GraphQL and POS integrity in order to ingest and to show the data correctly.

## Tasks
- [x]  PIS: copy the data manually until the new approach is not implemented
- [x] Configure the ETL config file (review Daniel PR to ETL repo)
- [x] Add the following fields to the GraphQL evidence endpoint (for istance):

```
    "interactingTargetFromSourceId": "ATR",
     "phenotypicConsequenceLogFoldChange": -0.94566,
     "phenotypicConsequenceFDR": 0.126694,
     "phenotypicConsequencePValue": 0.014117,
     "geneticInteractionMethod": "gemini",
     "geneticInteractionScore": -0.2,
     "geneticInteractionPValue": 0.004,
     "geneticInteractionFDR": 0.08
```
## Acceptance tests
- [ ] Verify the ingestion of the data using the GraphQL evidence endpoint modified

**Comment by DSuveges** [comment]
The weight of this datasource following the other example of other partner instance evidence is set to 0.5, it also reflects the "work in progress" nature of these sources.

```
  {id: "encore", weight: 0.5, data-type = "ot_partner", propagate = true},
```

**Comment by mbdebian** [comment]
This already is part of the previous PPP release.
