### ISSUE TITLE
Platform: update google project - to simplify infrastructure

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#190]
Currently, the platform runs over 4 projects with a number of extra components. Based on what has been learnt from the genetics work recently, we want to migrate this to a single new combined project with a simplified infrastructure:

This means we need to:
 - [ ] elasticsearch image
 - [ ] elasticsearch instance groups (one per region)
 - [ ] elasticsearch internal load balance (one per region)
 - [ ] api instance templates
 - [ ] api instance groups (one per region)
 - [ ] nginx proxy docker image
 - [ ] nginx instance groups (one per region)
 - [ ] global load balancer
 - [ ] update external url api.opentargets.io

**Comment by afaulconbridge** [comment]
This has been done, new infrastructure deployed for 19.02 and old infrastructure cleanup is on going.
