### ISSUE TITLE
Tool comparison - Locate interacting residues in the Drug-Target complex

### ISSUE THREAD

**Issue by MarineGirardey** [opentargets/platform#1920]
Next step of my internship

## Background

With molecules from parquet files, the PDB identifiers have been obtained with UniChem. From this, the PDB ID of structures in complex with the molecules has been gotten from the PDBe API. Finally, targets from a CSV file in FTP [pdb_chain_ensembl.csv](https://ftp.ebi.ac.uk/pub/databases/msd/sifts/csv/) has been extracted thanks to the PDB structure id.

## Tasks

Now the next task is to locate residues that are interacting with the compound in the Drug-Target complex using a pairwise distance calculation.

- [ ]  Find tools that can accomplish these calculations

- [ ] Install and learn how to use these tools

- [ ] Test the tools on the same structure and compare results

- [ ] Provide a detailed and meaningful comparison of these tools in order to choose the best one

**Comment by MarineGirardey** [comment]
# Tools to investigate

| Tools     | Easy to install    | Easy to use        | Rapidity           | Python Module      | Object Oriented    |
|-----------|--------------------|--------------------|--------------------|--------------------|--------------------|
| PILP      | :white_check_mark: | :grey_question:    | :grey_question:    | :white_check_mark: | :white_check_mark: |
| Arpeggio  | :white_check_mark: | :grey_question:    | :grey_question:    | :x:                | :x:                |
| LigPlot   | :grey_question:    | :grey_question:    | :grey_question:    | :x:                | :x:                |
| PUResNet  | :grey_question:    | :grey_question:    | :grey_question:    | :x:                | :x:                |
| ProLIF    | :grey_question:    | :grey_question:    | :grey_question:    | :x:                | :x:                |
| PyBioMed  | :grey_question:    | :grey_question:    | :grey_question:    | :white_check_mark: | :grey_question:    |
| MONN      | :grey_question:    | :grey_question:    | :grey_question:    | :x:                | :x:                |
| biobb     | :grey_question:    | :grey_question:    | :grey_question:    | :white_check_mark: | :grey_question:    |


:white_check_mark: : Good
:yellow_circle: : Could be better
:x: : Not good

**Comment by d0choa** [comment]
Just for reference, I looked at arpeggio some time ago and it's just a wrapper around some biopython functions. Just for reference -> [code here](https://github.com/PDBeurope/arpeggio/blob/0d1d14a506cd55ea7861f28325a52ed5e4b0bd68/arpeggio/core/interactions.py#L168)
