### ISSUE TITLE
Set up a GCP service account for the data team

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/platform#1970]
As a developer, I want to have a common GCP service account for the data team with the relevant permissions because I want to access Platform and Genetics data comfortably from a VM or a Dataproc cluster.

I expect to be able to run common tasks as evidence generation, metrics generation, EDA from that account.

## Background

When using my account, I usually encounter permission issues when accessing data or setting up a cluster in Genetics. 

For tasks as EDA or generating Genetics evidence, I want to be able to spin up a cluster in `open-targets-eu-dev` and access the data in `open-targets-genetics` and `open-targets-genetics-dev` without running into these type of problems.

## Tasks
Without having gone into much detail about the exact steps, the tasks are presumably:

- [ ] Create a service account in `open-targets-eu-dev`. Currently there is one `evidence-datasource-parsers` that we could modify.
- [ ] Grant access to the members of the @opentargets/data-team
- [ ] Configure permissions to the buckets of the above mentioned projects with the support of the @opentargets/be-team

**Comment by d0choa** [comment]
I added to the compute engine default account in `open-targets-eu-dev` named `42626...` Cloud storage admin privileges in `open-targets-genetics-dev`.

This works from my dataproc cluster

```
base ❯ gcloud config list
[core]
account = 4262********-compute@developer.gserviceaccount.com
disable_usage_reporting = True
project = open-targets-eu-dev

Your active configuration is: [default]

ochoa@do-phoenix-m ~
base ❯ gsutil ls gs://genetics-portal-dev-staging/v2d/220210/
gs://genetics-portal-dev-staging/v2d/220210/
gs://genetics-portal-dev-staging/v2d/220210/ld_analysis_input.tsv
gs://genetics-portal-dev-staging/v2d/220210/locus_overlap.parquet
gs://genetics-portal-dev-staging/v2d/220210/studies.parquet
gs://genetics-portal-dev-staging/v2d/220210/toploci_betas_fixed.parquet
gs://genetics-portal-dev-staging/v2d/220210/trait_efo-2021-02-14.parquet
gs://genetics-portal-dev-staging/v2d/220210/finemapping.parquet/
gs://genetics-portal-dev-staging/v2d/220210/ld.parquet/
gs://genetics-portal-dev-staging/v2d/220210/toploci_bad_betas2.parquet/
```

@ireneisdoomed feel free to go for a more elegant solution or stick to this. Let me know so we tidy up everything accordingly.

**Comment by DSuveges** [comment]
> I added to the compute engine default account [...] Cloud storage admin privileges in open-targets-genetics-dev.

I don't think any more elegant solution could exists. This is exactly what we wanted.
