### ISSUE TITLE
Use preemptible machines in deployed infrastructure

### ISSUE THREAD

**Issue by mbdebian** [opentargets/platform#1980]
As a developer I want to be able to do an infrastructure deployment on preemptible machines because the use case for that deployment is fault tolerant, and doing it this way reduces its operational cost.

## Background

This issue is related to #1978 , this way, that permanent development deployment will have a smaller impact in the operational cost

## Tasks

- [x] Extend Clickhouse provisioner to support a preemptible flag
- [x] Extend Elasticsearch provisioner to support a preemptible flag
- [x] Extend API provisioner to support a preemptible flag
- [x] Extend Web App provisioner to support a preemptible flag
- [x] Extend the root module provisioner to support the preemptible flag for the different components in the infrastructure
- [x] Do the Same for PPP
- [ ] Do the Same for Genetics
