### ISSUE TITLE
Improve specificity and confidence of associations

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/platform#293]
We want to investigate what the effect of global_stats is and whether there are other, simpler ways to 'trim' low-confidence associations (not for 18.12!). Assessment of low confidence associations has been started [here](https://docs.google.com/presentation/d/1lqpv7w1ZQ4if5l79dITiBaFFpuCPKdkmXZVRzseoKXI/edit#slide=id.p).

**Comment by MichaelaEBI** [comment]
A summary of my findings so far can be found here: https://docs.google.com/document/d/1oNS4ZrSExVweD39Je7LC8PgPPu2ImlzKON-7U3CCJVc/edit

**Comment by MichaelaEBI** [comment]
To do items after a meeting with Ian are as follows:
- [ ] Remove global_stats from the pipeline (which will result in an additional 0.5 mio associations)
- [ ] Change the weight factor for atlas data from 0.5 to 0.2
- [ ] Do not propagate atlas data (253,061 indirect associations have a single evidence string from atlas - with 2, 3, … 10 evidence strings from atlas there are 75982, 28045, 15048, 8455, 5835, 3464, 2695, 1982, 1520 = 143,026 additional associations)
