### ISSUE TITLE
Pipeline refactor: Remove external data use (API, etc)

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#325]
To improve reproducibility, use of external data sources (e.g. APIs, databases, git repositories) in the pipeline needs to be removed. Instead, there will be a pre-generation step where the external source is "frozen" into a static file, that can then be hosted under our control at a specific location for use by the pipeline.

The pipeline will access these frozen assets by downloading them locally, and then processing them as files. This download and storage will be handled by the Makefile to ensure reproducibility, avoid unnecessary duplication of actions, and improve performance since network bandwidth is often a limitation.

Subtasks:
- [x] opentargets/platform#278 ensembl
- [x] opentargets/platform#326 gene plugin hgnc
- [x] opentargets/platform#327 reactome
- [x] opentargets/platform#328 hpa
- [x] opentargets/platform#329 gene plugin and Search step chembl
- [x] opentargets/platform#379 gene plugin mousephenotypes
- [x] opentargets/platform#389 efo phenotypes
- [x] opentargets/platform#391 eco score modifiers

**Comment by afaulconbridge** [comment]
A list of URLs called by the pipeline can be retrieved by the `--log-http` option, and processed with `scripts/filter_http_logs.py` to remove calls to elasticsearch. Note that this only records http traffic via the requests library, so may not capture everything particularly access via transitive dependencies.

**Comment by afaulconbridge** [comment]
I've added the external APIs I know about via the http logging. There may be others lurking in the code - we should try running the pipeline without internet access (e.g. in a docker container with external networking disabled) to check once these are fixed.

**Comment by afaulconbridge** [comment]
Another issue is `json_schema`. Currently this is read from a GitHub version URL, which should not change and should be under our control. We may however decide that it needs to be more rigorously controlled e.g. by being fixed inside the Docker image.

**Comment by afaulconbridge** [comment]
This will need some coordination with opentargets/platform#146 harmonize user configuration

**Comment by afaulconbridge** [comment]
All of these seem to be done now, so closing this issue. If more appear in future, new issue(s) should be created for them.
