### ISSUE TITLE
Rewrite pipeline to replace redis queue with pypeln

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#361]
We are removing the Redis queue system and replacing it with a third party library pypeln. This will make it more maintainable, easier to run, and more performant.

This is the epic ticket to track the various sub-tasks.

- [x] hpa opentargets/platform#360
- [x] gene opentargets/platform#362
- [x] search opentargets/platform#365
- [x] ddr opentargets/platform#364
- [x] association opentargets/platform#423

**Comment by afaulconbridge** [comment]
Subtasks:

- [ ] opentargets/platform#360
- [ ] opentargets/platform#362
- [ ] opentargets/platform#364
- [ ] opentargets/platform#365
