### ISSUE TITLE
Roadmap: Target Annotation - Target safety

### ISSUE THREAD

**Issue by EPetsalaki** [opentargets/platform#411]
**Summary**
On-target adverse effects are a major contributor to drug candidate attrition due to precinical or clinical toxicity ([Brennan 2017](https://drive.google.com/open?id=1VkkC7ggSrqxmlP_om3tNAwrDIe2rwiPe)). Therefore, an early assessment of target safety is an important step in selecting a drug target candidate.
We will investigate how to include information on target safety on the Open Targets platform. 

**How**
Information on target safety will be added in two phases.
1. Curation of publications that provide information on targets with known safety issues.
2. A target safety pipeline will be implemented to combine different data sources into a safety score.

**Tickets associated with the different phases**

1. Curation of publications that provide information on targets with known safety issues
- [x] Initial data research 
#396 Compile list of targets with potential safety concerns
- [x]  #412 Prepare data for targets with known safety concerns for Open Targets pipeline
- [x] #460 + #461 Specify where and how safety warnings will be shown in OT Platform
- [x] Implement data injection
- [ ] #460 + #461  Front end changes

2. Target safety pipeline 
- [x] Initial data source research
- [ ] Develop the target safety pipeline
- [ ] Specify where and how safety score will be used in OT Platform
- [ ] Implement data injection
- [ ] Front end changes

See the notes from related meetings [here](https://docs.google.com/document/d/12wOYFDFRUKN_9xkBkFGj90v9P3g_zToGnls_Jpc7ElQ/edit).

**Comment by EPetsalaki** [comment]
Additional literature for known safety risks provided by Anne Hershey (CHEMBL) (HeCaTos project). See the collected lists of interesting targets [here](https://drive.google.com/open?id=1fURLaSbs8HkQjY1-b2szBf-HFZRfECwp). 
This includes tables of targets important for safety, but not necessarily linked to an ADR. Additionally, the mode of action (activation/inhibition) is not specified in all tables. Including this information will require:
- [ ] modifying the organisation of the known safety literature tables as well as the corresponding json schema. 
- [ ] Front end changes to include this additional safety information
