### ISSUE TITLE
Prepare data for targets with known safety concerns for Open Targets pipeline

### ISSUE THREAD

**Issue by EPetsalaki** [opentargets/platform#412]
**Preparation of target safety data for the Open Targets pipeline**

Data extracted from the following papers:
1. http://www.sciencedirect.com/science/article/pii/S1056871916301472
2. https://www.nature.com/articles/nrd3845
3. https://www.ncbi.nlm.nih.gov/pubmed/28453775

**Tasks**
- [x] Generate separate tables for each paper with collected information.
- [x] Map tissue terminology to Uberon terms.
- [x] Map adverse effects terms used in papers to EFO or HPO terms; if none is available use MeSH term temporarily and request new term from EFO.

_Previous related issue in target safety worklow:_ #396 Compile list of targets with potential safety concerns.

**Comment by EPetsalaki** [comment]
Known adverse effects tables + tissue & effect mapping collected in one file [here](https://drive.google.com/open?id=1YNxdMOBrHtMTPCRQOYyve25eqdh8RYzIgzpdzrGwzMY).
Overview of complete adverse effect mapping [here](https://drive.google.com/open?id=1LXjBXGsXAc6KlrG90csKcX5piHfF0jPTj8Tah5fpmeY).
To do: request terms not currently in EFO using the Webulous templates.

**Comment by EPetsalaki** [comment]
EFO term request github issue [here](https://github.com/EBISPOT/efo/issues/398)

**Comment by EPetsalaki** [comment]
Final mappings [here](https://docs.google.com/spreadsheets/d/1GTlynaoDOFHiWEiKOKaOOaZPI-EtLAEJcbwZU23UBBI/edit#gid=0).
