### ISSUE TITLE
Roadmap: Specify scope of OTAR2-048

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/platform#425]
The OTAR2-048 project will provide data on protein function and how variants (potentially) affect protein function. Slides from the February 2019 project meeting can be found [here.](https://docs.google.com/presentation/d/1klM4VwvXsHgL-4E70YLREPl2yKmpHJysEr7akKV5CeA/edit#slide=id.p1)

Next steps:
- [x] Define fields in summary of normal protein function (meeting on Feb 05, 2019)
- [ ] Correct info on slides 3 & 5 relating to data from IntAct and the Complex Portal (meeting on Feb 05, 2019)
- [ ] Define summary for variants that (potentially) affect protein function
- [ ] Define minimal information to specify a variant
- [ ] Assess list of variants that can be provided by OTAR2-048 (How many of the proteins and how many of the variants are associated with diseases in Open Targets?)
- [ ] Assess coverage of variant-disease and protein-disease associations that could be provided by OTAR2-048
- [ ] Assess protein complex lists from Protein Portal, ChEMBL & PDBe (meeting on Feb 05, 2019)

**Comment by MichaelaEBI** [comment]
The structure of the JSON documents is under development [here](https://docs.google.com/document/d/16XOnoyWrH6b4AfFkOvQ2F97yXrJrActLb7reQNUATRk/edit#heading=h.ue07i7ygg7cp).
