### ISSUE TITLE
Refactor platform pipeline

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#445]
A more detailed of the task and the work involved will soon be added to this ticket

Legacy work:
- [x] Docker
- [x] make
- [x] CI
- [ ]  target to extend test coverage to 75% - strategy to achieve to be defined under separate ticket
- [ ] contribution guidelines i.e. pull requests, code review, logging, etc. #503
- [x] +modularity & -duplication e.g. ontology, validation
- [ ] automated per-step QC - framework in place, need to nail down definition of tests https://github.com/opentargets/platform/issues/66
#515 

2. Ensure reproducibility - avoid API calls, use distributable files
- [x] #325 

3. Enable easy and transparent configuration of more evidence for a given data type or data source.
- [x] #146 
- [x] #532
- [ ] #581 - Configuration of data type and data source

**Comment by hammer** [comment]
As part of this refactoring, could the communication of the roadmap and release model be included?

I appreciate that this repo has been set up to collect issues across repos, the issues are well labeled, and that there are a large number of custom issue labels to choose from. I also appreciate the use of calendar versioning and the [technical notes](https://docs.targetvalidation.org/technical-pipeline/technical-notes) for recent releases.

However, while it is possible to see which issues are in progress, and to look at which branches exist for each repo, there are no issue labels for which issues are targeted for a specific upcoming release. I'm not sure how releases are planned internally, but for outside developers, it would be wonderful to see what's planned for the next few releases. It could be helpful to use GitHub Project boards for this purpose, though it's certainly not necessary.

It's also not easy to discern the motivation for the [releases](https://github.com/opentargets/data_pipeline/releases) made between the major two-month releases, though the [change log](https://docs.targetvalidation.org/technical-pipeline/change-log) helps a bit. Would it be possible to write up a paragraph for each of those releases to include in the repo release history?

**Comment by ElaineMcA** [comment]
Hi Jeff,

I wanted to acknowledge your feedback and suggestions - very much appreciated.  

We are working through our technical roadmap and have a couple of team sessions scheduled to review and update in more depth.   We can certainly share that, once available and also see what we can do to make annotations associated with releases clearer within the repo.

To date, release intentions for the next release are grouped under release tags within ZenHub.  

For more direct visibility, it should not be a problem to use the milestones directly within GitHub.  I can take a look at that with the team to see what works.

Best regards,

Elaine

**Comment by d0choa** [comment]
Closing and starting a new ticket on the pipeline refactor where we increase clarity on the task and workload. We'll factor in the contributions from related-sciences
