### ISSUE TITLE
Roadmap: Batch search - Implement an asynchronous backend dispatcher

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#524]
There are three stages for completion under this epic:

**Step 1: Backend implementation:**

- [x] Infrastructure to be set-up

- [x] API implementation to support

- [x] Check Redis queue configuration to not drop oldest entries (queue conf) 

- [ ] Integration in the infrastructure

**- [ ] Step 2: Implement batch search script to execute the batch search in the front end.**
This will require BE to consult with FE (@LucaFumis) to:

- resolve name of target
- implement query in multiples places
- pull together in batch report shell 

(Note: As part of this process, the referenced tickets will be reviewed to check if any may be resolved as part of this process: )

**- [ ] Step 3: Update python client to support the new batch search**

Once steps  1-2 above are completed, this will enable front end batch search code to be replaced by FE team, pending resource availability.

**Comment by cmalangone** [comment]
This task needs just to set up a deployment strategy.
*) How many workers? 
*) Redis on gcp?

The code for REST API is stored in the branch:
cm_524_batch_search_with_celery
The worker is available in the repository
https://github.com/opentargets/platform-batch-search-worker-service

**Comment by d0choa** [comment]
As agreed with @cmalangone and @mkarmona, we'll review batch search in July once other tasks have been completed.

**Comment by d0choa** [comment]
no work is expected in batch search
