### ISSUE TITLE
Target profile page rewrite: Prepare variants for testing

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#623]
There are now links for the two variants as below:
* [Variant 1](https://platform-app.netlify.com/target/ENSG00000091831)
* [Variant 2](https://gp-blue--platform-app.netlify.com/target/ENSG00000091831)

Since branching, tweaks have been made to Variant 1, which need to be merged into Variant 2. Ideally, the decision should be made soon after intergration day as to which is kept and which is dropped, since Variant 2 has some differences (to loading structure, for example).

**Comment by peatroot** [comment]
The tweaks in Variant 1, but yet to do in Variant 2 are:
* add Bibliography section
* add Target Safety section
* add additional links in header (GeneCards, HGNC, CRISPR depmap)

Have I missed any @d0choa?

**Comment by d0choa** [comment]
There are a few other fixes that @mirandaio and @andrewhercules have worked on. For an up-to-date list check [here](https://github.com/opentargets/platform/milestone/15?closed=1).

At the time of writing this comment:
- [ ] bibliography section - 2 minor changes pending #540 open
- [ ] target safety section - #620 open
- [ ] additional links - TEPs (#509 closed), HGNC and GeneCards (#553 closed)
- [ ] mouse phenotypes -  parsing genotypes (#528 closed)
- [ ] protein interactions - logic behind boolean state fixed (#525 closed)
- [ ] dynamic import of js libraries -  done for litemol, pending for expression atlas and protvista (#624 open)

**Comment by LucaFumis** [comment]
Changes to bibliography section were documented with commits under issue #542

**Comment by d0choa** [comment]
@mirandaio already changed to the Google Cloud deployed GraphQL in the `gp-mw-dnd-sections` and the `gp-blue` branches
