### ISSUE TITLE
Pipeline QC: Automated QC after each step of the pipeline

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#66]
**Summary**
The plan is generate QC metrics while the pipeline is running to ensure the pipeline is running as intended. We started monitoring certain metrics for each release in early 2018 on [this GitHub data_release repository wiki page](https://github.com/opentargets/data_release/wiki/OT011a-Data-Metrics-&-Plots). To move away from manually updating mark-up tables on the wiki page, we started a google sheet and explored more metrics that cold be monitored. These metrics have been generated for the [18.08](https://docs.google.com/spreadsheets/d/1qhIm8D5nCSaV6fQgybsYGb6oBb3EZXkq6bHmmfaCecw/edit#gid=0) and [18.10](https://docs.google.com/spreadsheets/d/1JkGIgDMYBEAFvvLz9nfbUrdZZ5pWiFXk1kwnTS4OZUY/edit#gid=426292169) data releases. There was also a data QC meeting in August 2018 and the notes can be found [here](https://docs.google.com/document/d/1RPurMV9cgK-YYpTCwT4aXOMVWaDgU-jklPlaPDBRpiM/edit#heading=h.6hthdjo51rxj). These documents are very much a work in progress and will be the basis for the more detailed specification of what the automated QC should look like.

**Work in progress**

- [x] Document current status of QC here (see summary above, add details about --qc and --metrics steps)
- [ ] Define the [workflow for QC of evidence strings](https://docs.google.com/presentation/d/1BV46XFNUBJ_4vYR2W8BHVD0IlodVg4G_H6TJ_ObEqEE/edit#slide=id.p)
- [ ] Define the [workflow for QC of base data (look-up tables)](https://docs.google.com/presentation/d/1BV46XFNUBJ_4vYR2W8BHVD0IlodVg4G_H6TJ_ObEqEE/edit#slide=id.g4538d33ad6_1_2) 
- [ ] Specify implementation details and steps

**QC-related tickets on GitHub**
- [Pipeline QC: Re-enable automated QC post 18.10](https://github.com/opentargets/platform/issues/205) - need to define implementation details first.
- [Pipeline QC: Automated QC distribution of scores](https://github.com/opentargets/platform/issues/194) - this might be good in the context of comparing data between releases (score distribution, new and 'lost' associations, targets and diseases)
- [Pipeline QC: Document --qc and --metrics steps](https://github.com/opentargets/platform/issues/214)

---
Initial use case: @gkos-bio commented on [Tue Aug 07 2018]
The description of this issue is based on my experience running the pipeline.
Overall, the stability has increased over time. 
On the last run, we observed that the Reactome step didn't fail but also didn't have the correct information. As a consequence, the facet served on the association page didn't contain the right data and were classified as 'Others'.

This ticket is to propose to develop a set of QC after each step to ensure that the lookup tables contain the right information.

---

**Comment by afaulconbridge** [comment]
Something to include is gene plugin results - to check if they injected anything or not.

**Comment by MichaelaEBI** [comment]
These gene plugins can already be checked and are recorded on the first sheet of the magical metrics document:
- chemicalprobes.probeminer
- chemicalprobes.portalprobes
- hallmarks
- cancerbiomarkers
- mouse_phenotypes.phenotypes
- tractability

I think we can add reactome to this list. The tricky bit will be to define how to check that a plugin worked.

**Comment by d0choa** [comment]
This issue is still ongoing and we'll proceed with a fresh start to the problem.
We are working on a system to systematically get metrics for any previous / current / candidate release, that can help to scrutinise the data sanity before and after running the pipeline
