### ISSUE TITLE
19.09 Release issues

### ISSUE THREAD

**Issue by cmalangone** [opentargets/platform#731]
DATA PIPELINE
- [x] Issue with the name of the temporary file
     Info: The issue was related with the temporary file and the delete option set to False.
     State: FIXED
- [x] Anydbm fails when the key is unicode
    Info: issue related with py3 and py2 (string vs unicode)
    State: FIXED
- [x] Elastic Search returns 10000 hits by default. (raised by Search step)
    Info: Elastic search DSL uses extra to add the field track_total_hits
    Eg. extra(track_total_hits=True)
    State: FIXED (tbc)
- [x] Uniprot_ids not complete in OT:
    Info: https://github.com/opentargets/platform/issues/701
    State: FIXED 
- [ ] Duplicated labels in facets:
     https://github.com/opentargets/platform/issues/729
     State: Progress 
 
REST API 
- [x] Besthit endpoint result was wrong
   State: FIXED
- [x] Stats main page wrong
   Added a new query (elastic search stats. track_total_hits is not precise)
   State: FIXED
- [x] Elastic Search returns 10000 hits by default.
    ** Different endpoint evidence
    Info: the solution is add track_total_hits
    Status: FIXED (tbc)
- [x] Fix free text search
    The query was not working with ES7 (fixed with MC)
    Status: FIXED (tbc)
- [x] The association and evidence dumps contain only 10000 entries 
    Info: Missing track_total_hits
    Status: FIXED (tbc)
- [ ] DrugEvidence issue:
    Info: https://github.com/opentargets/platform/issues/682#issuecomment-528287215
    Adam is fixing it
    Status: Progress

INFRASTRUCTURE
- [x] ES7 Snapshot not created. Issue with IP/DNS docker image
    https://github.com/opentargets/platform/issues/663
    Info: Moved the curl POST in the mcp script
    Status: FIXED (tbc)

**Comment by andrewhercules** [comment]
Ticket closed as #682 and #729 have been moved to the 19.11 release milestone
